### ISSUE TITLE
panic: validation failed for "Note" due to missing ItemsKeyID:

### ISSUE THREAD

**Issue by holzi-x** [jonhadfield/sn-dotfiles#13]
Just re-started with sn-dotfiles version [0.1.2-ce2278c] but having a hard time. When i try to read the status (or add a filee or whatever) i get this error:
```
2021/11/12 07:47:45 gosn-v2 cache | Sync | using db in '/home/username/.sn-dotfiles/sn-dotfiles-738031a2.db
2021/11/12 07:47:45 gosn-v2 | Sync | PageSize 0
2021/11/12 07:47:45 gosn-v2 | Sync | attempt 1
2021/11/12 07:47:45 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:45 gosn-v2 | syncItemsViaAPI | using default limit: 150
2021/11/12 07:47:45 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:45 gosn-v2 | syncItemsViaAPI | cursor is empty
2021/11/12 07:47:45 gosn-v2 | syncItemsViaAPI | making request: {"api":"20200115","items":[],"compute_integrity":true,"limit":150}
2021/11/12 07:47:46 gosn-v2 | makeSyncRequest | request took: 594.262119ms
2021/11/12 07:47:46 gosn-v2 | makeSyncRequest | sync of 66 req bytes succeeded with: 200 OK
2021/11/12 07:47:47 gosn-v2 | makeSyncRequest | response read took 1.897764101s
2021/11/12 07:47:47 gosn-v2 | makeSyncRequest | response size 563277 bytes
2021/11/12 07:47:47 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 2.492321789s
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | Retrieved 164 items
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjY1LjM5Nzg5Mw==
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNTg4MDU5NzI5Ljc0OTUyMg==
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | got cursor MjoxNTg4MDU5NzI5Ljc0OTUyMg==
2021/11/12 07:47:47 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjY1LjM5Nzg...
2021/11/12 07:47:48 gosn-v2 | makeSyncRequest | request took: 297.326615ms
2021/11/12 07:47:48 gosn-v2 | makeSyncRequest | sync of 143 req bytes succeeded with: 200 OK
2021/11/12 07:47:48 gosn-v2 | makeSyncRequest | response read took 480.221928ms
2021/11/12 07:47:48 gosn-v2 | makeSyncRequest | response size 234025 bytes
2021/11/12 07:47:48 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 777.820924ms
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | Retrieved 150 items
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjY3Ljk0OTY1OA==
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNTk5MTk2ODk3LjIwODk5Mg==
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | got cursor MjoxNTk5MTk2ODk3LjIwODk5Mg==
2021/11/12 07:47:48 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjY3Ljk0OTY...
2021/11/12 07:47:49 gosn-v2 | makeSyncRequest | request took: 317.540358ms
2021/11/12 07:47:49 gosn-v2 | makeSyncRequest | sync of 143 req bytes succeeded with: 200 OK
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | response read took 1.906091696s
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | response size 869558 bytes
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 2.223861692s
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Retrieved 150 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjY4LjcwOTYzNw==
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNTk5NjgxOTE2LjMxNjAzMw==
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | got cursor MjoxNTk5NjgxOTE2LjMxNjAzMw==
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjY4LjcwOTY...
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | request took: 163.682535ms
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | sync of 143 req bytes succeeded with: 200 OK
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | response read took 632.436246ms
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | response size 292694 bytes
2021/11/12 07:47:51 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 796.248685ms
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Retrieved 150 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjcwLjkxODQ1
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNTk5NjgxOTI1LjQyNjM4Nw==
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | got cursor MjoxNTk5NjgxOTI1LjQyNjM4Nw==
2021/11/12 07:47:51 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjcwLjkxODQ...
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | request took: 267.725367ms
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | sync of 139 req bytes succeeded with: 200 OK
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | response read took 544.919536ms
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | response size 294114 bytes
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 812.943545ms
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | Retrieved 150 items
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjcxLjgxNjA1Mw==
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNTk5ODA1NzUzLjk2MzkyNQ==
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | got cursor MjoxNTk5ODA1NzUzLjk2MzkyNQ==
2021/11/12 07:47:52 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjcxLjgxNjA...
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | request took: 318.910644ms
2021/11/12 07:47:52 gosn-v2 | makeSyncRequest | sync of 143 req bytes succeeded with: 200 OK
2021/11/12 07:47:53 gosn-v2 | makeSyncRequest | response read took 613.144128ms
2021/11/12 07:47:53 gosn-v2 | makeSyncRequest | response size 339156 bytes
2021/11/12 07:47:53 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 932.210379ms
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | Retrieved 150 items
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjcyLjUzODM4NQ==
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNjEzMDcwMTgyLjM4NzE5NA==
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | got cursor MjoxNjEzMDcwMTgyLjM4NzE5NA==
2021/11/12 07:47:53 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjcyLjUzODM...
2021/11/12 07:47:53 gosn-v2 | makeSyncRequest | request took: 312.980002ms
2021/11/12 07:47:53 gosn-v2 | makeSyncRequest | sync of 143 req bytes succeeded with: 200 OK
2021/11/12 07:47:54 gosn-v2 | makeSyncRequest | response read took 380.18994ms
2021/11/12 07:47:54 gosn-v2 | makeSyncRequest | response size 185756 bytes
2021/11/12 07:47:54 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 693.613853ms
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | Retrieved 150 items
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | setting input sync token: MjoxNjM2Njk5NjczLjYzMjk5NA==
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | setting input cursor token: MjoxNjI2NzcyOTQ4LjM2NDEyNA==
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | SyncInput: NextItem: 0
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | input.PageSize: 150
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | items to put 0
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | got cursor MjoxNjI2NzcyOTQ4LjM2NDEyNA==
2021/11/12 07:47:54 gosn-v2 | syncItemsViaAPI | making request: {"limit":150,"items":[],"compute_integrity":true,"sync_token":"MjoxNjM2Njk5NjczLjYzMjk...
2021/11/12 07:47:54 gosn-v2 | makeSyncRequest | request took: 204.617906ms
2021/11/12 07:47:54 gosn-v2 | makeSyncRequest | sync of 143 req bytes succeeded with: 200 OK
2021/11/12 07:47:55 gosn-v2 | makeSyncRequest | response read took 1.066991196s
2021/11/12 07:47:55 gosn-v2 | makeSyncRequest | response size 591193 bytes
2021/11/12 07:47:55 gosn-v2 | makeSyncRequest | response body closed
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | makeSyncRequest took: 1.271765825s
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | Saved 0 items
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | Retrieved 131 items
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | Unsaved 0 items
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | Conflict 0 items
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | final item put: 0 total items to put: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | syncItemsViaAPI | setting out.LastItemPut to: 0
2021/11/12 07:47:55 gosn-v2 | Sync | took 10.076423119s to get all items
2021/11/12 07:47:55 gosn-v2 | Sync | post processing took 10.60889ms
2021/11/12 07:47:55 gosn-v2 | Sync | sync token: MjoxNjM2Njk5NjY1LjM5Nzg5Mw==
2021/11/12 07:47:55 gosn-v2 | Sync | duration 10.087268073s
panic: validation failed for "Note" due to missing ItemsKeyID: "bf21dfc5-fd6a-4eed-8be5-a41a2716bb3d"

goroutine 1 [running]:
github.com/jonhadfield/gosn-v2.Sync(0xc0000ea9a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20210719172924-55b0cdb35616/sync.go:118 +0xd3c
github.com/jonhadfield/gosn-v2/cache.Sync(0xc0005eec80, 0x853800, 0x0, 0x9d8b00, 0xc000099240)
	/go/pkg/mod/github.com/jonhadfield/gosn-v2@v0.0.0-20210719172924-55b0cdb35616/cache/cache.go:362 +0xd85
github.com/jonhadfield/dotfiles-sn/sn-dotfiles.Status(0xc0005eec80, 0xc0000260f5, 0xd, 0x0, 0x0, 0x0, 0x1f4, 0x1, 0xc0000d4b00, 0x32, ...)
	/home/circleci/project/sn-dotfiles/status.go:22 +0x45
main.startCLI.func2(0xc0000ea6e0, 0xc000170000, 0xc000170050)
	/home/circleci/project/cmd/sn-dotfiles/main.go:113 +0x405
github.com/urfave/cli.HandleAction(0x8aa940, 0xc0000bc680, 0xc0000ea6e0, 0xc0000ea6e0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x94147b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x94f4dc, 0x18, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc0001101c0, 0xc00009a150, 0x3, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.startCLI(0xc00009a150, 0x3, 0x3, 0xc000000180, 0xc000044740, 0x468c25, 0xc000000180, 0x200000003)
	/home/circleci/project/cmd/sn-dotfiles/main.go:453 +0x16ba
main.main()
	/home/circleci/project/cmd/sn-dotfiles/main.go:24 +0x57
```

I did delete the config folder from the old implementation. I have no dotfiles folder in my standardnotes account. Any hint what might be the issue? Im am running a debian11

**Comment by jonhadfield** [comment]
If your account was created before Nov 2020, it's possible you still have items that use the old encryption version. Since then, all accounts will only use the new version that includes an ItemsKeyID for all encrypted items.
To force update to the new version, simply update your password. SN will then re-encrypt every item with the new encryption version.
It's also possible that you have some corrupt items, in which case the official app will ignore them but mine would panic. I've just released a new version that will simply ignore them, like the official app will: https://github.com/jonhadfield/sn-dotfiles/releases/tag/0.1.4

**Comment by holzi-x** [comment]
Must be the corrupt items issue. 0.1.4 is working, thanks a lot!

**Comment by jonhadfield** [comment]
Thanks for letting me know.
